//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthData", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    public partial class AuthData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string passwordField;
        
        private string usernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatEntity", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    public partial class StatEntity : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int LosesField;
        
        private string PlayernameField;
        
        private int UserIDField;
        
        private int WinsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Loses
        {
            get
            {
                return this.LosesField;
            }
            set
            {
                this.LosesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Playername
        {
            get
            {
                return this.PlayernameField;
            }
            set
            {
                this.PlayernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wins
        {
            get
            {
                return this.WinsField;
            }
            set
            {
                this.WinsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseAction", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    public partial class BaseAction : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string actionField;
        
        private int baseidField;
        
        private string resultField;
        
        private string tokenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int baseid
        {
            get
            {
                return this.baseidField;
            }
            set
            {
                this.baseidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1")]
public interface IService1
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendAuthData", ReplyAction="http://tempuri.org/IService1/SendAuthDataResponse")]
    string SendAuthData(WcfService.AuthData data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendAuthData", ReplyAction="http://tempuri.org/IService1/SendAuthDataResponse")]
    System.Threading.Tasks.Task<string> SendAuthDataAsync(WcfService.AuthData data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserList", ReplyAction="http://tempuri.org/IService1/GetUserListResponse")]
    WcfService.StatEntity[] GetUserList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserList", ReplyAction="http://tempuri.org/IService1/GetUserListResponse")]
    System.Threading.Tasks.Task<WcfService.StatEntity[]> GetUserListAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpgradeBase", ReplyAction="http://tempuri.org/IService1/UpgradeBaseResponse")]
    string UpgradeBase(WcfService.BaseAction msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpgradeBase", ReplyAction="http://tempuri.org/IService1/UpgradeBaseResponse")]
    System.Threading.Tasks.Task<string> UpgradeBaseAsync(WcfService.BaseAction msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BaseAction", ReplyAction="http://tempuri.org/IService1/BaseActionResponse")]
    string BaseAction(WcfService.BaseAction msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BaseAction", ReplyAction="http://tempuri.org/IService1/BaseActionResponse")]
    System.Threading.Tasks.Task<string> BaseActionAsync(WcfService.BaseAction msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
    string GetData(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
    System.Threading.Tasks.Task<string> GetDataAsync(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendData", ReplyAction="http://tempuri.org/IService1/SendDataResponse")]
    string SendData(string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendData", ReplyAction="http://tempuri.org/IService1/SendDataResponse")]
    System.Threading.Tasks.Task<string> SendDataAsync(string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDummyUserData", ReplyAction="http://tempuri.org/IService1/GetDummyUserDataResponse")]
    WcfService.AuthData GetDummyUserData();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDummyUserData", ReplyAction="http://tempuri.org/IService1/GetDummyUserDataResponse")]
    System.Threading.Tasks.Task<WcfService.AuthData> GetDummyUserDataAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
    WcfService.CompositeType GetDataUsingDataContract(WcfService.CompositeType composite);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
    System.Threading.Tasks.Task<WcfService.CompositeType> GetDataUsingDataContractAsync(WcfService.CompositeType composite);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string SendAuthData(WcfService.AuthData data)
    {
        return base.Channel.SendAuthData(data);
    }
    
    public System.Threading.Tasks.Task<string> SendAuthDataAsync(WcfService.AuthData data)
    {
        return base.Channel.SendAuthDataAsync(data);
    }
    
    public WcfService.StatEntity[] GetUserList()
    {
        return base.Channel.GetUserList();
    }
    
    public System.Threading.Tasks.Task<WcfService.StatEntity[]> GetUserListAsync()
    {
        return base.Channel.GetUserListAsync();
    }
    
    public string UpgradeBase(WcfService.BaseAction msg)
    {
        return base.Channel.UpgradeBase(msg);
    }
    
    public System.Threading.Tasks.Task<string> UpgradeBaseAsync(WcfService.BaseAction msg)
    {
        return base.Channel.UpgradeBaseAsync(msg);
    }
    
    public string BaseAction(WcfService.BaseAction msg)
    {
        return base.Channel.BaseAction(msg);
    }
    
    public System.Threading.Tasks.Task<string> BaseActionAsync(WcfService.BaseAction msg)
    {
        return base.Channel.BaseActionAsync(msg);
    }
    
    public string GetData(int value)
    {
        return base.Channel.GetData(value);
    }
    
    public System.Threading.Tasks.Task<string> GetDataAsync(int value)
    {
        return base.Channel.GetDataAsync(value);
    }
    
    public string SendData(string username, string password)
    {
        return base.Channel.SendData(username, password);
    }
    
    public System.Threading.Tasks.Task<string> SendDataAsync(string username, string password)
    {
        return base.Channel.SendDataAsync(username, password);
    }
    
    public WcfService.AuthData GetDummyUserData()
    {
        return base.Channel.GetDummyUserData();
    }
    
    public System.Threading.Tasks.Task<WcfService.AuthData> GetDummyUserDataAsync()
    {
        return base.Channel.GetDummyUserDataAsync();
    }
    
    public WcfService.CompositeType GetDataUsingDataContract(WcfService.CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContract(composite);
    }
    
    public System.Threading.Tasks.Task<WcfService.CompositeType> GetDataUsingDataContractAsync(WcfService.CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContractAsync(composite);
    }
}
