//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfservice
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthData", Namespace="http://schemas.datacontract.org/2004/07/wcfservice")]
    public partial class AuthData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string passwordField;
        
        private string usernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatEntity", Namespace="http://schemas.datacontract.org/2004/07/wcfservice")]
    public partial class StatEntity : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BasenameField;
        
        private int LosesField;
        
        private string PlayernameField;
        
        private int ResearchPointsField;
        
        private int UserIDField;
        
        private int WinsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Basename
        {
            get
            {
                return this.BasenameField;
            }
            set
            {
                this.BasenameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Loses
        {
            get
            {
                return this.LosesField;
            }
            set
            {
                this.LosesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Playername
        {
            get
            {
                return this.PlayernameField;
            }
            set
            {
                this.PlayernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResearchPoints
        {
            get
            {
                return this.ResearchPointsField;
            }
            set
            {
                this.ResearchPointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wins
        {
            get
            {
                return this.WinsField;
            }
            set
            {
                this.WinsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/wcfservice")]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BaseIDField;
        
        private string BasenameField;
        
        private bool IsActiveField;
        
        private int LevelField;
        
        private int OwnerIDField;
        
        private wcfservice.ResourcesData ResourcesField;
        
        private wcfservice.StructureEntity[] StructuresField;
        
        private wcfservice.UnitsData[] UnitsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BaseID
        {
            get
            {
                return this.BaseIDField;
            }
            set
            {
                this.BaseIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Basename
        {
            get
            {
                return this.BasenameField;
            }
            set
            {
                this.BasenameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level
        {
            get
            {
                return this.LevelField;
            }
            set
            {
                this.LevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OwnerID
        {
            get
            {
                return this.OwnerIDField;
            }
            set
            {
                this.OwnerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wcfservice.ResourcesData Resources
        {
            get
            {
                return this.ResourcesField;
            }
            set
            {
                this.ResourcesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wcfservice.StructureEntity[] Structures
        {
            get
            {
                return this.StructuresField;
            }
            set
            {
                this.StructuresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wcfservice.UnitsData[] Units
        {
            get
            {
                return this.UnitsField;
            }
            set
            {
                this.UnitsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourcesData", Namespace="http://schemas.datacontract.org/2004/07/wcfservice")]
    public partial class ResourcesData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int creditsField;
        
        private int energyField;
        
        private string instanceField;
        
        private double neutrinoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int credits
        {
            get
            {
                return this.creditsField;
            }
            set
            {
                this.creditsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int energy
        {
            get
            {
                return this.energyField;
            }
            set
            {
                this.energyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instance
        {
            get
            {
                return this.instanceField;
            }
            set
            {
                this.instanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double neutrino
        {
            get
            {
                return this.neutrinoField;
            }
            set
            {
                this.neutrinoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructureEntity", Namespace="http://schemas.datacontract.org/2004/07/wcfservice")]
    public partial class StructureEntity : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BaseIDField;
        
        private int LevelField;
        
        private string TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BaseID
        {
            get
            {
                return this.BaseIDField;
            }
            set
            {
                this.BaseIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level
        {
            get
            {
                return this.LevelField;
            }
            set
            {
                this.LevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnitsData", Namespace="http://schemas.datacontract.org/2004/07/wcfservice")]
    public partial class UnitsData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int countField;
        
        private string instanceField;
        
        private string typeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instance
        {
            get
            {
                return this.instanceField;
            }
            set
            {
                this.instanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WithToken", Namespace="http://schemas.datacontract.org/2004/07/wcfservice")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcfservice.SquadAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcfservice.BaseAction))]
    public partial class WithToken : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string tokenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SquadAction", Namespace="http://schemas.datacontract.org/2004/07/wcfservice")]
    public partial class SquadAction : wcfservice.WithToken
    {
        
        private string actionField;
        
        private string keyField;
        
        private int toField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseAction", Namespace="http://schemas.datacontract.org/2004/07/wcfservice")]
    public partial class BaseAction : wcfservice.WithToken
    {
        
        private string actionField;
        
        private int baseidField;
        
        private string resultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int baseid
        {
            get
            {
                return this.baseidField;
            }
            set
            {
                this.baseidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SquadEntity", Namespace="http://schemas.datacontract.org/2004/07/wcfservice")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcfservice.AuthData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcfservice.StatEntity[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcfservice.StatEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcfservice.BaseEntity[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcfservice.BaseEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcfservice.ResourcesData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcfservice.StructureEntity[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcfservice.StructureEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcfservice.UnitsData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcfservice.UnitsData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcfservice.BaseAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcfservice.WithToken))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcfservice.SquadAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcfservice.SquadEntity[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    public partial class SquadEntity : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FinishTimeField;
        
        private string KeyField;
        
        private int MoveFromField;
        
        private int MoveToField;
        
        private int OwnerIDField;
        
        private int StartTimeField;
        
        private object[] UnitsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinishTime
        {
            get
            {
                return this.FinishTimeField;
            }
            set
            {
                this.FinishTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MoveFrom
        {
            get
            {
                return this.MoveFromField;
            }
            set
            {
                this.MoveFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MoveTo
        {
            get
            {
                return this.MoveToField;
            }
            set
            {
                this.MoveToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OwnerID
        {
            get
            {
                return this.OwnerIDField;
            }
            set
            {
                this.OwnerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Units
        {
            get
            {
                return this.UnitsField;
            }
            set
            {
                this.UnitsField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1")]
public interface IService1
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendAuthData", ReplyAction="http://tempuri.org/IService1/SendAuthDataResponse")]
    string SendAuthData(wcfservice.AuthData data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendAuthData", ReplyAction="http://tempuri.org/IService1/SendAuthDataResponse")]
    System.Threading.Tasks.Task<string> SendAuthDataAsync(wcfservice.AuthData data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPlayerList", ReplyAction="http://tempuri.org/IService1/GetPlayerListResponse")]
    wcfservice.StatEntity[] GetPlayerList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPlayerList", ReplyAction="http://tempuri.org/IService1/GetPlayerListResponse")]
    System.Threading.Tasks.Task<wcfservice.StatEntity[]> GetPlayerListAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBaseList", ReplyAction="http://tempuri.org/IService1/GetBaseListResponse")]
    wcfservice.BaseEntity[] GetBaseList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBaseList", ReplyAction="http://tempuri.org/IService1/GetBaseListResponse")]
    System.Threading.Tasks.Task<wcfservice.BaseEntity[]> GetBaseListAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BaseAction", ReplyAction="http://tempuri.org/IService1/BaseActionResponse")]
    string BaseAction(wcfservice.BaseAction msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BaseAction", ReplyAction="http://tempuri.org/IService1/BaseActionResponse")]
    System.Threading.Tasks.Task<string> BaseActionAsync(wcfservice.BaseAction msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBaseStructures", ReplyAction="http://tempuri.org/IService1/GetBaseStructuresResponse")]
    wcfservice.StructureEntity[] GetBaseStructures(wcfservice.BaseAction msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBaseStructures", ReplyAction="http://tempuri.org/IService1/GetBaseStructuresResponse")]
    System.Threading.Tasks.Task<wcfservice.StructureEntity[]> GetBaseStructuresAsync(wcfservice.BaseAction msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBaseUnits", ReplyAction="http://tempuri.org/IService1/GetBaseUnitsResponse")]
    wcfservice.UnitsData[] GetBaseUnits(wcfservice.BaseAction obj);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBaseUnits", ReplyAction="http://tempuri.org/IService1/GetBaseUnitsResponse")]
    System.Threading.Tasks.Task<wcfservice.UnitsData[]> GetBaseUnitsAsync(wcfservice.BaseAction obj);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBaseInfo", ReplyAction="http://tempuri.org/IService1/GetBaseInfoResponse")]
    wcfservice.BaseEntity GetBaseInfo(wcfservice.BaseAction msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBaseInfo", ReplyAction="http://tempuri.org/IService1/GetBaseInfoResponse")]
    System.Threading.Tasks.Task<wcfservice.BaseEntity> GetBaseInfoAsync(wcfservice.BaseAction msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSquads", ReplyAction="http://tempuri.org/IService1/GetSquadsResponse")]
    wcfservice.SquadEntity[] GetSquads(wcfservice.SquadAction obj);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSquads", ReplyAction="http://tempuri.org/IService1/GetSquadsResponse")]
    System.Threading.Tasks.Task<wcfservice.SquadEntity[]> GetSquadsAsync(wcfservice.SquadAction obj);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SquadAction", ReplyAction="http://tempuri.org/IService1/SquadActionResponse")]
    string SquadAction(wcfservice.SquadAction obj);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SquadAction", ReplyAction="http://tempuri.org/IService1/SquadActionResponse")]
    System.Threading.Tasks.Task<string> SquadActionAsync(wcfservice.SquadAction obj);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DbStatus", ReplyAction="http://tempuri.org/IService1/DbStatusResponse")]
    void DbStatus();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DbStatus", ReplyAction="http://tempuri.org/IService1/DbStatusResponse")]
    System.Threading.Tasks.Task DbStatusAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string SendAuthData(wcfservice.AuthData data)
    {
        return base.Channel.SendAuthData(data);
    }
    
    public System.Threading.Tasks.Task<string> SendAuthDataAsync(wcfservice.AuthData data)
    {
        return base.Channel.SendAuthDataAsync(data);
    }
    
    public wcfservice.StatEntity[] GetPlayerList()
    {
        return base.Channel.GetPlayerList();
    }
    
    public System.Threading.Tasks.Task<wcfservice.StatEntity[]> GetPlayerListAsync()
    {
        return base.Channel.GetPlayerListAsync();
    }
    
    public wcfservice.BaseEntity[] GetBaseList()
    {
        return base.Channel.GetBaseList();
    }
    
    public System.Threading.Tasks.Task<wcfservice.BaseEntity[]> GetBaseListAsync()
    {
        return base.Channel.GetBaseListAsync();
    }
    
    public string BaseAction(wcfservice.BaseAction msg)
    {
        return base.Channel.BaseAction(msg);
    }
    
    public System.Threading.Tasks.Task<string> BaseActionAsync(wcfservice.BaseAction msg)
    {
        return base.Channel.BaseActionAsync(msg);
    }
    
    public wcfservice.StructureEntity[] GetBaseStructures(wcfservice.BaseAction msg)
    {
        return base.Channel.GetBaseStructures(msg);
    }
    
    public System.Threading.Tasks.Task<wcfservice.StructureEntity[]> GetBaseStructuresAsync(wcfservice.BaseAction msg)
    {
        return base.Channel.GetBaseStructuresAsync(msg);
    }
    
    public wcfservice.UnitsData[] GetBaseUnits(wcfservice.BaseAction obj)
    {
        return base.Channel.GetBaseUnits(obj);
    }
    
    public System.Threading.Tasks.Task<wcfservice.UnitsData[]> GetBaseUnitsAsync(wcfservice.BaseAction obj)
    {
        return base.Channel.GetBaseUnitsAsync(obj);
    }
    
    public wcfservice.BaseEntity GetBaseInfo(wcfservice.BaseAction msg)
    {
        return base.Channel.GetBaseInfo(msg);
    }
    
    public System.Threading.Tasks.Task<wcfservice.BaseEntity> GetBaseInfoAsync(wcfservice.BaseAction msg)
    {
        return base.Channel.GetBaseInfoAsync(msg);
    }
    
    public wcfservice.SquadEntity[] GetSquads(wcfservice.SquadAction obj)
    {
        return base.Channel.GetSquads(obj);
    }
    
    public System.Threading.Tasks.Task<wcfservice.SquadEntity[]> GetSquadsAsync(wcfservice.SquadAction obj)
    {
        return base.Channel.GetSquadsAsync(obj);
    }
    
    public string SquadAction(wcfservice.SquadAction obj)
    {
        return base.Channel.SquadAction(obj);
    }
    
    public System.Threading.Tasks.Task<string> SquadActionAsync(wcfservice.SquadAction obj)
    {
        return base.Channel.SquadActionAsync(obj);
    }
    
    public void DbStatus()
    {
        base.Channel.DbStatus();
    }
    
    public System.Threading.Tasks.Task DbStatusAsync()
    {
        return base.Channel.DbStatusAsync();
    }
}
